spring:
  application:
    name: persistence

  datasource:
    url: jdbc:postgresql://localhost:5432/building_permits
    username: app
    password: app

  flyway:
    enabled: true

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: persistence
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "ch.studior2.buildingpermitmonitor.*"
